travis:
  secure:
    BINSTAR_TOKEN: Gl6yODbafDiIECrfq1ElR9B+V2v19S2tOoIXhN2y4W53T8Hn8Y2db/G3UgeM3OcoW3DhlgHzflwoXNX0KCwrdoFileQegSIAIJh/1aZ9n9f7g8l7PbbMcq/SvfHyJkW+Cm+6y4uAZc9zkOTet2gVK802LdrVtP7XWdAoSTh/UphdH65rfNB69U8FaMcU1u2r+lLcR92yRAKq3zpBZGuBm+sl0GvLCAECr4TCGzzPCnDfTmYLTBnk3ZAJH6XwoSXkIspJnXFxK495z3UecBCv6vATGLdtN66FSNKtfi0RfISXh1jUS/nIg6pBRWe1foAkBlk8NrqYdkgLIwbyLb306hYzfMUbuAS7w7+Rc9xTHb+foUB1p0rH+1IaThRtxvm+H1xhtIPdQ5ESC3JUc5zdcpumHTCxMHIfV/k7yjOwQf7blLsHn7pYmR1wg+X6i3lFjK5i9W7kIZTOGE3MDzJ0ifjYBtvn1KT04AAppgrLavWYPKP6P0ho9j8weuPi96Usj72kjU/5f3LRX2ZFkafmqp1B/GiHBlkK6a0BK6lqwj1gJkrf3cFEJApoGMn74jch+1G2YOCBa+XufagHrVHkEMeMZP1CIKRbYqK7hYivmXIdsioUEHSuyRnioFqBZVgdI28IFPg/11igSeeMUBWXqt6dCLosySE+g3C128vkjoA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
